spring:
  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
#  freemarker:
#    template-loader-path: classpath:/WEB-INF/templates/
#    suffix: .ftlh
#    check-template-location: false
#    cache: false
#    settings:
#      template_update_delay: 1ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
#  mvc:
#    static-path-pattern: /static/**



com:
 csbaic:
  auth:
    jwt:
      key-value: jwt:key:jd-union-xxxxxxxxxxxxxxxx

application:
  # 微信信息配置
 mini-app:
   appid: wxf9ea0760e7c44b57 #微信小程序appid
   secret: xxx #替换成自己的密钥
 sms:
   access-key-id: LTAI4FxiVViLhNEU4qiP2JGf
   access-secret: xxx #替换成自己的密钥
   sign-name: 佰创信息
   template-code: SMS_182910815

 goods-qrcode-Logo: classpath:/jd_qr_logo.png

 
mybatis-plus:
  mapper-locations:
    - classpath*:/com/csbaic/jd/mapper/**/*.xml
 #   - classpath*:/com/csbaic/rbac/jdbc/com.csbaic.rbac.dto.mapper/**/*.xml
#  global-config:
#    db-config:
#      logic-delete-field: deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0


logging:
  level:
    com.csbaic.jd.service.order.fetcher: error