server:
  port: 8888
spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
        - id: service-consumer
          uri: http://localhost:8060
          predicates:
            - name: Path
              args:
                pattern: "/consumer"
        - id: service-provider
          uri: http://localhost:8070
          predicates:
            - name: Path
              args:
                pattern: "/provider"
