spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://6ex23trrS9:3306/wx-manage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 6ex23trrS9

springfox:
    documentation:
        swagger-ui:
            enabled: false
